Repository Team-LionHeart/LionHeart-iOS, pull requests merged in 2023-11, with the labels that each got.

#163 [REFACTOR] LoginViewController MVVM-C로 변경 (#162)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/Combine+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/ViewControllerServiceable.swift
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHToast/LHToast.swift
  LionHeart-iOS/LionHeart-iOS/Global/Utils/LoadingIndicator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/LoginViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/AuthCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/CurriculumCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/AuthFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/AuthFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewControllers/MyPageViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁민재, 🦁의성, 🦁찬미, ♻️Refactoring

#165 [REFACTOR] Auth관련 VC들 MVVM-C(Combine)으로 변경 (#164)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/Combine+.swift
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHNavigationBarView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Adaptor/AuthAdaptor.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/CompleteOnbardingViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/LoginViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/OnboardingViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/SplashViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/AuthCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/AuthCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/AuthFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/SplashFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/AuthFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/SpalshFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/NavigationInterface/CompleteOnboardingNavigation.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingPageType/OnboardingPageType.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/CompleteOnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/GetFetalNicknameViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/GetPregnancyViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewModels/CompleteOnboardingViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewModels/CompleteOnboardingViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewModels/GetFetalNicknameViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewModels/GetFetalNicknameViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewModels/GetPregnancyViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewModels/GetPregnancyViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewModels/OnboardingViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewModels/OnboardingViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewModelImpl.swift
Labels: 🦁민재, 🦁의성, 🦁찬미, ♻️Refactoring

#182 [REFACTOR] 아티클뷰 DiffableDataSource로 변경 및 MVVM(Combine)-C로 리팩토링 (#167)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Cells/ThumnailTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Model/ArticleBlockType.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewModel/ArticleDetailViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewModel/ArticleDetailViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/ArticleControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/ArticleCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/ArticleFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/ArticleFactory.swift
Labels: 🦁민재, ♻️Refactoring

#170 [REFACTOR] ChallengeVC를 DiffableDataSource와 MVVM(Combine)으로 리팩터링
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/Cells/ChallengeDayCheckCollectionViewCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/ChallengeViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/ChallengeFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/ChallengeFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Views/TodayArticleView.swift
Labels: 🦁의성, ♻️Refactoring

#172 [REFACTOR] TodayViewController MVVM(Combine)-C로 리팩터링
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/Combine+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/ViewControllerServiceable.swift
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/ViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Global/Utils/GesturePublisher.swift
  LionHeart-iOS/LionHeart-iOS/Global/Utils/GestureSubscription.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/ChallengeViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/OnboardingViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/TodayViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/TodayFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/TodayFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Views/TodayArticleView.swift
Labels: 🦁의성, ♻️Refactoring

#183 [REFACTOR] ArticleCategory DiffableDataSource로 변경 및 MVVM-C 리팩 (#174)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Cells/ArticleCategoryCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Model/ArticleCategoryDiffableDataSource.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Model/ArticleCategoryDiffableModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Model/ArticleCategoryModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewModel/ArticleCategoryViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewModel/ArticleCategoryViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/ArticleCategoryViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/ArticleCategoryCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/ArticleCategortFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/ArticleCategortFactory.swift
Labels: 🦁민재, ♻️Refactoring

#178 [REFACTOR] CurriculumListWeek(주차별 아티클뷰)를 Diffable 및 MVVM(Combine)-C로 리팩터링 (#177)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/CurriculumArticleByWeekControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/CurriculumCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekHeaderView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumListByWeekCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Diffable/CurriculumListWeekDiffableModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Model/CurriculumWeekBackgroundDummy.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewModel/CurriculumListWeekViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewModel/CurriculumListWeekViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Views/CurriculumListByCategoryTableView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/CurriculumFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/CurriculumFactory.swift
Labels: 🦁민재, 🦁의성, ♻️Refactoring

#185 [REFACTOR] Tabbar Coordinator리팩터링(메서드분리)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UITabbarItem+.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/TabbarCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/TabBar/TabBarViewController.swift
Labels: 🦁의성, ♻️Refactoring

#181 [REFACTOR] BookmarkVC를 Diffable 및 MVVM(Combine)-C로 리팩터링
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Network/Service/BookmarkServiceImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Cells/BookmarkDetailCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Cells/BookmarkListCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Model/BookmarkModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Model/BookmarkRow.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewModel/BookViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewModel/BookmarkViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/BookmarkViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/BookmarkFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/BookmarkFactory.swift
Labels: 🦁민재, 🦁의성, 🦁찬미, ♻️Refactoring

#187 [REFACTOR] CurriculumView Diffable 및 MVVM(Combine)-C로 리팩터링 (#179)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/CurriculumControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Diffable/CurriculumViewDiffableModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Model/CurriculumDummyData.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewModel/CurriculumViewViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewModel/CurriculumViewViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Views/CurriculumTableViewHeaderView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/CurriculumFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/CurriculumFactory.swift
Labels: 🦁민재, 🦁의성, 🦁찬미, ♻️Refactoring

#192 [REFACTOR] runloop, cell binding방식, 토스트메세지, loadingView 적용
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewModel/ChallengeViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewModel/ChallengeViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewController/MyPageViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewModel/MyPageViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/CompleteOnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewModels/OnboardingViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewModels/OnboardingViewModelImpl.swift
Labels: 🦁의성, ♻️Refactoring

#193 [REFACTOR] Runloop, cell binding방식, 토스트메세지, loadingView 적용 (#190)
  LionHeart-iOS/LionHeart-iOS/Global/Literals/NameSpace.swift
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHToast/LHToast.swift
  LionHeart-iOS/LionHeart-iOS/Global/UserDefault/UserDefaultToken.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/ArticleDetail/Cells/ThumnailTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/ArticleDetail/ViewController/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/ArticleDetail/ViewModel/ArticleDetailViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/ArticleListByCategory/ViewController/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/CurriculmumListWeek/Cell/CurriculumArticleByWeekTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/CurriculmumListWeek/ViewController/CurriculumListWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/CurriculmumListWeek/ViewModel/CurriculumListWeekViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewModel/CurriculumViewViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/ViewModel/LoginViewModelImpl.swift
Labels: 🦁민재, ♻️Refactoring

#194 [REFACTOR] Runloop, cell binding방식, 토스트메세지, loadingView 적용 (#191)
  LionHeart-iOS/LionHeart-iOS/Scenes/ArticleCategory/ViewController/ArticleCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/ArticleListByCategory/ViewController/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Cells/BookmarkListCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewController/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewModel/BookViewModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewModel/BookmarkViewModelImpl.swift
Labels: 🦁찬미, ♻️Refactoring

#196 [TEST] API Unit Test 관련 파일들 추가 (#195)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Network/Base/APIService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/CurriculmumListWeek/ViewModel/CurriculumListWeekViewModelImpl.swift
  LionHeart-iOS/LionHeart-iOSTests/Challenge/ServiceTests/ServiceTests.swift
  LionHeart-iOS/LionHeart-iOSTests/URLSessionStub/JSONLoader.swift
  LionHeart-iOS/LionHeart-iOSTests/URLSessionStub/URLSessionStub.swift
Labels: 🦁민재, 🦁의성, 🧪Test
