Repository Team-LionHeart/LionHeart-iOS, pull requests merged in 2023-07, with the labels that each got.

#4 [SETTING] 공용extension, 공용 protocol 설정 (#3)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/CALayer+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/Encodable+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIButton+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIControl+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIImage+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIStackView+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UITextField+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIView+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIViewController+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Literals/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Global/Literals/NameSpace.swift
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/CollectionViewCellRegisterDequeueProtocol.swift
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/DataTypeProtocol.swift
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/TableViewCellRegisterDequeueProtocol.swift
  LionHeart-iOS/LionHeart-iOS/Settings/Configurations/Config.swift
Labels: ⚙️Settings, 🦁의성

#6 [SETTING] 폴더에 시드파일 추가 (#5)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Literals/DummyModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Cells/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Cells/ArticleCategoryTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Views/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Views/ArticleCategoryView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Cells/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Cells/ArticleDetailTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Views/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Views/ArticleDetailView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/Cells/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/Cells/ArticleListByCategoryTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/Views/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/Views/ArticleListByCategoryView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByWeek/Cells/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByWeek/Cells/ArticleListByWeekTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByWeek/ViewControllers/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByWeek/ViewControllers/ArticleListByWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByWeek/Views/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByWeek/Views/ArticleListByWeekView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Cells/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Cells/BookMarkTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookMarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Views/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Views/BookMarkView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Views/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Views/CurriculumView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewControllers/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewControllers/MyPageViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Views/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Views/MyPageView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/Cells/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/Cells/OnboardingTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/Views/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/Views/OnboardingView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/TabBar/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/TabBar/TabBarViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Cells/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Cells/TodayTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Views/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Views/TodayView.swift
Labels: ⚙️Settings, 🦁의성

#10 [FEAT] NavigationBar 구현 (#7)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Enums/NavigationBarType.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIApplication+.swift
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHNavigationBarView.swift
  LionHeart-iOS/LionHeart-iOS/Global/Utils/.gitkeep
  LionHeart-iOS/LionHeart-iOS/Global/Utils/NavigationBarLayoutManager.swift
  LionHeart-iOS/LionHeart-iOS/Global/Utils/ScreenUtils.swift
Labels: ⚙️Settings, 🦁민재, ✨Feat

#12 [SETTING] Font, Color 구현 (#11)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Application/SceneDelegate.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/CGColor+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIColor+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIFont+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/Black.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/ComponentLionRed.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/Gray100.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/Gray1000.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/Gray200.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/Gray300.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/Gray400.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/Gray500.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/Gray600.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/Gray700.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/Gray800.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/Gray900.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/LionRed.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/White.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/background.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Utils/Font/Font.swift
  LionHeart-iOS/LionHeart-iOS/Global/Utils/Font/Pretendard-Bold.ttf
  LionHeart-iOS/LionHeart-iOS/Global/Utils/Font/Pretendard-Medium.ttf
  LionHeart-iOS/LionHeart-iOS/Global/Utils/Font/Pretendard-Regular.ttf
  LionHeart-iOS/LionHeart-iOS/Global/Utils/Font/Pretendard-SemiBold.ttf
  LionHeart-iOS/LionHeart-iOS/Global/Utils/Palette.swift
  LionHeart-iOS/LionHeart-iOS/ViewController.swift
Labels: ⚙️Settings, 🦁의성

#16 [FIX] Color Asset 네이밍 변경(#15)
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHNavigationBarView.swift
  LionHeart-iOS/LionHeart-iOS/Global/Utils/Palette.swift
Labels: ⚙️Settings, 🦁의성, 🐛Hotfix

#23 [FEAT] CurriculumView TableView 구현 (#19)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Model/CurriculumDummyData.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
Labels: 🦁성준, ✨Feat

#27 [FEAT] 커리큘럼뷰 UI 구현(#24)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/NSObject+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/1word.imageset/1word 1.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/1word.imageset/1word 2.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/1word.imageset/1word.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/1word.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/2word.imageset/2word 1.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/2word.imageset/2word 2.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/2word.imageset/2word.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/2word.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Vector1.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Vector1.imageset/Vector1.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/gradient1.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/gradient1.imageset/gradient1.png
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Model/CurriculumDummyData.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Views/CurriculumProgessTableViewHeaderView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Views/CurriculumTableViewHeaderView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Views/CurriculumUserInfoView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/TabBar/TabBarViewController.swift
Labels: 🦁성준, ✨Feat

#22 [FEAT] ExploreView UI구현 (#20)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_1.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_1.imageset/Group 48096344.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_1.imageset/Group 48096344@2x.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_1.imageset/Group 48096344@3x.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_2.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_2.imageset/Group 48096351.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_2.imageset/Group 48096351@2x.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_2.imageset/Group 48096351@3x.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_3.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_3.imageset/Group 48096345.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_3.imageset/Group 48096345@2x.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_3.imageset/Group 48096345@3x.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_4.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_4.imageset/Group 48096349.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_4.imageset/Group 48096349@2x.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_4.imageset/Group 48096349@3x.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_5.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_5.imageset/Group 48096353.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_5.imageset/Group 48096353@2x.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_5.imageset/Group 48096353@3x.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_6.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_6.imageset/Group 48096352.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_6.imageset/Group 48096352@2x.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_6.imageset/Group 48096352@3x.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_7.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_7.imageset/Group 48096350.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_7.imageset/Group 48096350@2x.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_7.imageset/Group 48096350@3x.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_8.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_8.imageset/Group 48096348.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_8.imageset/Group 48096348@2x.jpg
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Category_8.imageset/Group 48096348@3x.jpg
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Cells/ArticleCategoryCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Cells/ArticleCategoryTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Model/ArticleCategoryModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift
Labels: 🦁동현, ✨Feat, P2

#29 [FEAT] 아티클뷰 데이터 로직 구현 (#18)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Network/Base/BaseResponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/Base/NetworkError.swift
  LionHeart-iOS/LionHeart-iOS/Network/DTO/ArticleDetail/Response/ArticleDetail.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/KingfisherService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Model/ArticleBlockType.swift
Labels: 🦁민재, ✨Feat, P0

#34 [FEAT] 온보딩 구현 (#14)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Application/SceneDelegate.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/Float+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIApplication+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIPageViewController+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UITextField+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Literals/Constant.swift
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Onboarding/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHNavigationBarView.swift
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/NHUnderLine.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/Cells/OnboardingTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingComponent/ContainerView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingComponent/LHOnboardingButton.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingComponent/LHOnboardingDescriptionLabel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingComponent/LHOnboardingErrorLabel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingComponent/LHOnboardingPageViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingComponent/LHOnboardingTitleLabel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingComponent/LHProgressView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingComponent/LHRoundButton.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingComponent/NHOnboardingTextfield.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingComponent/RoundContainerView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingModel/UserOnboardingModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingPageType/OnboardingPageType.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingTextFieldResultType/OnboardingFetalNicknameTextFieldResultType.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingTextFieldResultType/OnboardingPregnancyTextFieldResultType.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/CompleteOnbardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/GetFetalNicknameViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/GetPregnancyViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/Views/OnboardingView.swift
  LionHeart-iOS/LionHeart-iOS/ViewController.swift
Labels: 🦁의성, ✨Feat, P0

#41 [FEAT] 투데이아티클 UI 구현 (#35)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Application/SceneDelegate.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UILabel+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIView+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Today/today_test_image.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Today/today_test_image.imageset/today_test_image.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Today/today_test_label.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Today/today_test_label.imageset/today_test_label.png
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHNavigationBarView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Cells/TodayTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Component/LHTodayArticleTitle.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Model/TodayModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Views/TodayArticleView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Views/TodayView.swift
Labels: 🦁의성, ✨Feat, P0

#45 [FEAT] Splash, LoginView 구현(#43)
  LionHeart-iOS/LionHeart-iOS/Application/Base.lproj/LaunchScreen.storyboard
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIButton+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Color/KakaoYellow.colorset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/TemporaryImage/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/TemporaryImage/kakaoImage.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/TemporaryImage/kakaoImage.imageset/kakaoImage.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/TemporaryImage/loginImage.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/TemporaryImage/loginImage.imageset/loginImage.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/TemporaryImage/loginImage.imageset/loginImage@2x.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/TemporaryImage/loginImage.imageset/loginImage@3x.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/TemporaryImage/temporary_splash_image.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/TemporaryImage/temporary_splash_image.imageset/temporary_splash_image.png
  LionHeart-iOS/LionHeart-iOS/Global/Utils/Palette.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift
Labels: 🦁의성, ✨Feat, P3

#51 [FEAT] 마이페이지 UI 구현
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Literals/ImageLiterals.swift
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/CollectionHeaderViewRegisterDequeueProtocol.swift
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/MyPage/ic_pen_color.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/MyPage/ic_pen_color.imageset/Property 1=ic_pen_red.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/MyPage/ic_pen_color.imageset/Property 1=ic_pen_red@2x.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/MyPage/ic_pen_color.imageset/Property 1=ic_pen_red@3x.png
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Cells/MyPageAppSettingCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Cells/MyPageCustomerServiceCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Cells/MyPageProfileCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Model/MyPageModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewControllers/MyPageViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Views/MyPageHeaderView.swift
Labels: 🦁찬미, ✨Feat, P2

#48 [FEAT] 공용 토스트메세지 구현(#46)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Application/SceneDelegate.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIWindow+.swift
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHToast/LHToast.swift
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHToast/LHToastView.swift
  LionHeart-iOS/LionHeart-iOS/ViewController.swift
Labels: ⚙️Settings, 🦁의성, ✨Feat, P1

#47 [FEAT] 주차별 리스트 뷰 UI 구현(버튼 기능 포함)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekRowZeroTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumListByWeekCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Model/CurriculumListByWeekData.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
Labels: 🦁성준, ✨Feat

#52 [FEAT] Splash에서 유저플로우 분기 (#13)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Application/SceneDelegate.swift
  LionHeart-iOS/LionHeart-iOS/Global/Literals/NameSpace.swift
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/Serviceable.swift
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/ViewControllerServiceable.swift
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/motion_logo.json
  LionHeart-iOS/LionHeart-iOS/Global/Utils/UserDefaultsManager.swift
  LionHeart-iOS/LionHeart-iOS/Global/Utils/setRootViewController.swift
  LionHeart-iOS/LionHeart-iOS/Network/Base/BaseResponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/Base/HttpMethod.swift
  LionHeart-iOS/LionHeart-iOS/Network/Base/NetworkError.swift
  LionHeart-iOS/LionHeart-iOS/Network/Base/NetworkErrorCode.swift
  LionHeart-iOS/LionHeart-iOS/Network/Base/NetworkRequest.swift
  LionHeart-iOS/LionHeart-iOS/Network/DTO/Auth/Token.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/AuthService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift
  LionHeart-iOS/LionHeart-iOS/Settings/Configurations/Config.swift
  LionHeart-iOS/LionHeart-iOS/Settings/Info.plist
Labels: 🦁민재, ✨Feat, P0

#54 [FEAT] 전체 Flow 연결 (#53)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Application/SceneDelegate.swift
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHNavigationBarView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Views/ArticleDetailTableView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewControllers/MyPageViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/CompleteOnbardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁의성, ✨Feat

#58 [FEAT] 온보딩 API 구현 (#55)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Application/AppDelegate.swift
  LionHeart-iOS/LionHeart-iOS/Application/Base.lproj/LaunchScreen.storyboard
  LionHeart-iOS/LionHeart-iOS/Application/SceneDelegate.swift
  LionHeart-iOS/LionHeart-iOS/Global/Enums/LoginType.swift
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/motion_logo.json
  LionHeart-iOS/LionHeart-iOS/Global/UserDefault/UserDefaultToken.swift
  LionHeart-iOS/LionHeart-iOS/Global/Utils/UserDefaultsManager.swift
  LionHeart-iOS/LionHeart-iOS/Network/Base/NetworkErrorCode.swift
  LionHeart-iOS/LionHeart-iOS/Network/DTO/Auth/LoginRequest.swift
  LionHeart-iOS/LionHeart-iOS/Network/DTO/Onboarding/SignUpRequest.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/AuthService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift
  LionHeart-iOS/LionHeart-iOS/ViewController.swift
Labels: 🦁민재, 🦁의성, 🦁찬미, ✨Feat, P0

#61 FEAT : 오늘의 아티클 API 연결 (#59)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Network/DTO/Today/TodayArticleResponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/ArticleService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Component/LHTodayArticleTitle.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Model/TodayModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Views/TodayArticleView.swift
Labels: 🦁의성, ✨Feat, P0

#67 [FIX] 메인아티클에 layer추가(#65)
  LionHeart-iOS/LionHeart-iOS/Application/SceneDelegate.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIView+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Today/MainArticleSeperateLine.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Today/MainArticleSeperateLine.imageset/MainArticleSeperateLine.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Today/today_image.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Today/today_image.imageset/today_image.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Today/today_test_image.imageset/today_test_image.png
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Views/TodayArticleView.swift
Labels: 🦁의성, ✨Feat, P0

#64 [FEAT] 아티클 상세뷰 API 연결 (#60)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/Serviceable.swift
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/motion_logo.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/motion_logo_final.json
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHToast/LHToast.swift
  LionHeart-iOS/LionHeart-iOS/Network/Base/NetworkRequest.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/ArticleService.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/AuthService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Model/TodayModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁민재, P0, 🌐Network

#69 [HOTFIX] TodayArticle DTO 변경 대응 (#68)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/progressbar_10m.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/progressbar_2m.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/progressbar_3m.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/progressbar_4m.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/progressbar_5m.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/progressbar_6m.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/progressbar_7m.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/progressbar_8m.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/progressbar_9m.json
  LionHeart-iOS/LionHeart-iOS/Network/DTO/Today/TodayArticleResponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/ArticleService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Model/TodayModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁의성, ✨Feat, P0

#81 [FEAT] 북마크 API 연결
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIViewController+.swift
  LionHeart-iOS/LionHeart-iOS/Network/DTO/Bookmark/Request/BookmarkRequest.swift
  LionHeart-iOS/LionHeart-iOS/Network/DTO/Bookmark/Response/BookmarkReponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/BookmarkService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Cells/BookmarkListCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Model/BookmarkModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
Labels: 🦁찬미, ✨Feat, P3, 🌐Network

#82 [FEAT] Curriculum뷰 API "커리큘럼 진척도 조회" 네트워크 연결
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Application/SceneDelegate.swift
  LionHeart-iOS/LionHeart-iOS/Network/DTO/Curriculum/CurriculumResponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/CurriculumViewService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Model/CurriculumDummyData.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Views/CurriculumUserInfoView.swift
Labels: 🦁성준, ✨Feat, 🌐Network

#88 [FEAT] ExploreView & DeatialView 연결
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumListByWeekCollectionViewCell.swift
Labels: 🦁찬미, ✨Feat, P2

#80 [FIX] 온보딩 플로우 엣지케이스 해결 (#79)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Network/Base/NetworkErrorCode.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/AuthService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift
Labels: 🦁민재, P0, 🌐Network

#92 [FEAT] 로딩뷰 구현 (#91)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Utils/LoadingIndicator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Settings/Info.plist
Labels: 🦁민재, ✨Feat, P3

#78 [CHORE] UI 디테일 일부 수정 #62
  LionHeart-iOS/LionHeart-iOS/Global/Enums/NavigationBarType.swift
  LionHeart-iOS/LionHeart-iOS/Global/Literals/ImageLiterals.swift
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Login/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Login/ic_kakao.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Login/ic_kakao.imageset/ic_kakao.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Login/ic_kakao.imageset/ic_kakao@2x.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Login/ic_kakao.imageset/ic_kakao@3x.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Login/kakao_login_img.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Login/kakao_login_img.imageset/img.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Login/kakao_login_img.imageset/img@2x.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Login/kakao_login_img.imageset/img@3x.png
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHNavigationBarView.swift
  LionHeart-iOS/LionHeart-iOS/Global/Utils/Font/Font.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Cells/BodyTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Cells/ChapterTitleTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Cells/EditorTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Cells/GeneralTitleTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift
Labels: 🦁민재, P0, 🧹Chore

#97 [FIX] Query String JSON Decoding Error hotfix (#96)
  LionHeart-iOS/LionHeart-iOS/Network/Base/NetworkRequest.swift
Labels: 🦁민재, 🦁의성, 🐛Hotfix

#70 [FEAT] ChallengeView UI 구현 및 Network 연결(#56)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/Level1.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/Level2.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/Level3.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/Level4.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Lotties/Level5.json
  LionHeart-iOS/LionHeart-iOS/Network/DTO/Challenge/ChallengeDataResponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/ChallengeService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/Cells/ChallengeDayCheckCollectionViewCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/Model/ChallengeData.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/Model/ChallengeDummy.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift
Labels: 🦁동현, ✨Feat, P2, 🌐Network, 🔨Fix

#89 [CHORE] 북마크 버튼 API 연결 (#83)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Network/DTO/ArticleDetail/Response/ArticleDetail.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/ArticleService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Cells/ThumnailTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Model/ArticleBlockType.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁민재, P0, 🌐Network

#99 [Feat] 탐색뷰 조회, 북마크 API, 커리큘럼 북마크 API 연결
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Network/DTO/ArticleListByCategory/ArticleListByCategoryResponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/DTO/Curriculum/CurriculumResponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/ArticleService.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/BookmarkService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Cells/ArticleCategoryCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/Model/ArticleCategoryModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift
Labels: 🦁찬미, ✨Feat, P3

#98 [FIX] UI디테일수정, 로딩뷰추가, gradient겹치는 문제 수정 #93
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Enums/NavigationBarType.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIView+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Literals/ImageLiterals.swift
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Today/TodayArticle_PointImage.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/Today/TodayArticle_PointImage.imageset/TodayArticle_PointImage.png
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/onboarding_complete_image.imageset/Contents.json
  LionHeart-iOS/LionHeart-iOS/Global/Resources/Assets.xcassets/onboarding_complete_image.imageset/onboarding_complete_image.png
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHNavigationBarView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingComponent/LHLoadingView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/OnboardingTextFieldResultType/OnboardingPregnancyTextFieldResultType.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/CompleteOnbardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/GetPregnancyViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Component/LHTodayArticleTitle.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/Views/TodayArticleView.swift
Labels: 🦁의성, P1, 🌐Network, 🔨Fix

#102 [FEAT] 로딩뷰 window최상단이 아닌 뷰계층으로 교체 (#101)
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/ViewControllerServiceable.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/KingfisherService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
Labels: 🦁민재, ✨Feat, P2

#106 [FIX] 북마크 삭제 이슈 및 마이페이지 레이아웃 조정 (#100)
  LionHeart-iOS/LionHeart-iOS/Network/Services/BookmarkService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Cells/BookmarkListCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Model/BookmarkModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewControllers/MyPageViewController.swift
Labels: 🦁찬미, P3, 🔨Fix

#105 [FIX] 디테일한 UI수정 #103
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
Labels: 🦁의성, P1, 🔨Fix

#107 [FEAT] LoadingView뷰 추가 (#104)
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/ViewControllerServiceable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁민재, ✨Feat, P2

#110 [FEAT] 마이페이지 API 연결 (#109)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Network/DTO/MyPage/MyPageResponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/MyPageService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Cells/MyPageProfileCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Model/MyPageModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewControllers/MyPageViewController.swift
Labels: 🦁찬미, ✨Feat, P3

#111 [FIX] 주차별 커리큘럼 조회 화면에서 오른쪽 버튼 클릭시 앱 터지는 에러 해결 (#108)
  LionHeart-iOS/LionHeart-iOS/Network/DTO/ArticleListByCategory/ArticleListByCategoryResponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/DTO/Curriculum/CurriculumResponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/ArticleService.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/CurriculumViewService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekRowZeroTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumListByWeekCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Model/CurriculumListByWeekData.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Settings/Info.plist
Labels: 🦁민재, 🐛Hotfix, P0

#115 [FIX] 1차 내부 QA (#114)
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIView+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIViewController+.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Views/ArticleDetailTableView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/Cells/ChallengeDayCheckCollectionViewCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁의성, P0, 🔨Fix

#116 [FIX] 1차 내부 QA
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIView+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIViewController+.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Views/ArticleDetailTableView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Cells/BookmarkListCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/Cells/ChallengeDayCheckCollectionViewCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumListByWeekCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁찬미, P2, P3, 🔨Fix

#118 [FIX] 1차 내부 QA (#113)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Application/AppDelegate.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Cells/ThumnailTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekRowZeroTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Model/CurriculumWeekBackgroundDummy.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
Labels: 🦁민재, P0, 🔨Fix

#119 [Fix] 커리큘럼메인에서 scrollToRow 분기처리(#117)
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
Labels: 🦁성준, 🐛Hotfix

#122 [CHORE] 레이아웃 수정 및 사용자 경험 증진 (#121)
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIButton+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIViewController+.swift
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHNavigationBarView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/Cells/BodyTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekRowZeroTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumArticleByWeekTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Cells/CurriculumTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/Views/CurriculumUserInfoView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁민재, ✨Feat, P0
