Repository Team-LionHeart/LionHeart-iOS, pull requests merged in 2023-10, with the labels that each got.

#137 [Refactor] #135 - 북마크 & 마이페이지 헤더뷰, 셀 디자인시스템 적용
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UICollectionViewCell+.swift
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/CollectionHeaderViewRegisterDequeueProtocol.swift
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHImageButton.swift
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHLabel.swift
  LionHeart-iOS/LionHeart-iOS/Global/Utils/Palette.swift
  LionHeart-iOS/LionHeart-iOS/Network/Manager/MyPageManagerImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Cells/BookmarkDetailCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Cells/BookmarkListCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Cells/MyPageAppSettingCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Cells/MyPageCustomerServiceCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Cells/MyPageProfileCollectionViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Model/MyPageModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewControllers/MyPageViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Views/MyPageHeaderView.swift
Labels: 🦁찬미, 🎨DesignSystem

#138 [REFACTOR] 디자인시스템 적용 및 추가 (#136)
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHImageButton.swift
  LionHeart-iOS/LionHeart-iOS/Global/UIComponents/LHLottie.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift
Labels: 🦁민재, ♻️Refactoring

#142 [ADD] ViewControllerable 프로토콜 추가 (#141)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/ViewControllerable.swift
Labels: 🦁민재, 🦁의성, 🦁찬미, ♻️Refactoring

#146 [REFACTOR] ArticleCategory, Challenge, Bookmark Factory Pattern 적용(#143)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ArticleCategoryCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/BookmarkCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ChallengeCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CurriculumCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/ArticleCategoryViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/BookmarkViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/ChallengeViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/ViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/TabbbarCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/TodayCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/ArticleCategortFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/BookmarkFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/ChallengeFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/ArticleCategortFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/BookmarkFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/ChallengeFactory.swift
Labels: 🦁의성, ✨Feat, ♻️Refactoring

#148 [REFACTOR] - Auth, Splash, Today factory pattern 적용 (#144)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/AppCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/AuthCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/AuthFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/SpalshFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/SplashCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/TabbbarCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/TodayCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/TodayFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/CompleteOnbardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁찬미, ♻️Refactoring

#147 [REFACTOR] Curriculum, MyPage, Article Coordinator에 Factory Pattern 적용 (#145)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ArticleCategoryCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ArticleCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ArticleFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ArticleFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/BookmarkCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ChallengeCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CurriculumCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CurriculumFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CurriculumFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/ArticleControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/CurriculumArticleByWeekControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/CurriculumControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/ViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/MyPageControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/MyPageFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/MyPageFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/MypageCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/TabbbarCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/TodayCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewControllers/MyPageViewController.swift
Labels: 🦁민재, ♻️Refactoring

#150 [REFACTOR] Factory Pattern도입(#149)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/ArticleCategoryViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/ArticleControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/BookmarkViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/ChallengeViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/CompleteOnbardingViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/CurriculumArticleByWeekControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/CurriculumControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/LoginViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/MyPageControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/OnboardingViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/SplashViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/TodayViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/Interface/ViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/ArticleFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/AuthFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/CurriculumFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/MyPageFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/SplashFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/TodayFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/ArticleFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/AuthFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/CurriculumFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/MyPageFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/SpalshFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/TodayFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/CompleteOnbardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁민재, 🦁의성, 🦁찬미, ✨Feat, ♻️Refactoring

#154 [REFACTOR] today coordinator에 adaptor pattern 적용
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Scenes/Adaptor/TodayAdaptor.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/TodayViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/TodayCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/AppCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/ArticleCategoryCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/ArticleCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/AuthCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/BookmarkCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/ChallengeCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/CurriculumCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/MypageCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/SplashCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/TabbbarCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/TodayCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/TodayFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/TodayFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/NavigationInterface/Common/ExpireNavigation.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁민재, 🦁의성, 🦁찬미, ✨Feat, ♻️Refactoring

#157 [REFACTOR] Splash, Auth, ArticleCategory Coordinator에 Adaptor Pattern적용(#156)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Scenes/Adaptor/ArticleCategoryAdaptor.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Adaptor/AuthAdaptor.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Adaptor/SplashAdaptor.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Adaptor/TodayAdaptor.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/ArticleCategoryViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/ArticleListByCategoryViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/CompleteOnbardingViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/LoginViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/OnboardingViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/SplashViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/ControllerableInterface/TodayViewControllerable.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/ArticleCategoryCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/AuthCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/SplashCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/TodayCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/AppCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/ArticleCategoryCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/AuthCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/MypageCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/SplashCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorInterface/TabbbarCoordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/ArticleCategortFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/AuthFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/SplashFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryImpl/TodayFactoryImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/ArticleCategortFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/AuthFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/SpalshFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Factory/FactoryInterface/TodayFactory.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/NavigationInterface/Common/PopNavigation.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/CompleteOnbardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁의성, ♻️Refactoring

#161 [REFACTOR] Adaptor Pattern 도입 (#153)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Application/SceneDelegate.swift
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/Coordinator.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/AppCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/ArticleCategoryCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/BookmarkCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/ChallengeCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/CurriculumCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/SplashCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/TabbarCoordinatorImpl.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Coordinator/CoordinatorImpl/TodayCoordinatorImpl.swift
Labels: 🦁민재, ♻️Refactoring
