Repository Team-LionHeart/LionHeart-iOS, pull requests merged in 2023-09, with the labels that each got.

#128 [REFACTOR] API 레이어 분리 (#127)
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Application/SceneDelegate.swift
  LionHeart-iOS/LionHeart-iOS/Global/Protocols/Serviceable.swift
  LionHeart-iOS/LionHeart-iOS/Network/API/AuthAPI.swift
  LionHeart-iOS/LionHeart-iOS/Network/API/MyPageAPI.swift
  LionHeart-iOS/LionHeart-iOS/Network/Base/APIService.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/AuthMyPageServiceWrapper.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/AuthService.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/MyPageService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/Model/MyPageModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewControllers/MyPageViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
  LionHeart-iOS/LionHeart-iOS/ViewController.swift
Labels: 🦁민재, 🦁의성, ♻️Refactoring

#130 [Refactor] #129 - 북마크 네트워크 레이어 분리
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIViewController+.swift
  LionHeart-iOS/LionHeart-iOS/Network/API/BookmarkAPI.swift
  LionHeart-iOS/LionHeart-iOS/Network/DTO/Bookmark/Response/BookmarkReponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/BookmarkService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁찬미

#132 [REFACTOR]전체 DI적용
  LionHeart-iOS/LionHeart-iOS.xcodeproj/project.pbxproj
  LionHeart-iOS/LionHeart-iOS/Application/SceneDelegate.swift
  LionHeart-iOS/LionHeart-iOS/Global/Enums/Badge.swift
  LionHeart-iOS/LionHeart-iOS/Global/Extensions/UIViewController+.swift
  LionHeart-iOS/LionHeart-iOS/Network/Base/APIService.swift
  LionHeart-iOS/LionHeart-iOS/Network/DTO/Challenge/ChallengeDataResponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/DTO/Today/TodayArticleResponse.swift
  LionHeart-iOS/LionHeart-iOS/Network/Manager/ArticleDetailManagerImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Manager/ArticleListByCategoryMangerImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Manager/BookmarkMangerImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Manager/ChallengeManagerImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Manager/CurriculumListManagerImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Manager/CurriculumManagerImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Manager/LoginMangerImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Manager/MyPageManagerImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Manager/OnboardingManagerImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Manager/SplashManagerImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Manager/TodayManagerImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Service/ArticleServiceImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Service/AuthServiceImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Service/BookmarkServiceImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Service/ChallengeServiceImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Service/CurriculumServiceImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Service/MyPageServiceImpl.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/ArticleService.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/AuthMyPageServiceWrapper.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/BookmarkService.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/ChallengeService.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/CurriculumViewService.swift
  LionHeart-iOS/LionHeart-iOS/Network/Services/KingfisherService.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleCategory/ViewControllers/ArticleCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleDetail/ViewControllers/ArticleDetailViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByCategory/ViewControllers/ArticleListByCategoryViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByWeek/Cells/ArticleListByWeekTableViewCell.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByWeek/ViewControllers/ArticleListByWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Article/ArticleListByWeek/Views/ArticleListByWeekView.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/Model/BookmarkModel.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/BookMark/ViewControllers/BookmarkViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/Model/ChallengeData.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Challenge/ViewController/ChallengeViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumListByWeekViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Curriculum/ViewControllers/CurriculumViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Login/LoginViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/MyPage/ViewControllers/MyPageViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Onboarding/ViewControllers/OnboardingViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Splash/SplashViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/TabBar/TabBarViewController.swift
  LionHeart-iOS/LionHeart-iOS/Scenes/Today/ViewControllers/TodayViewController.swift
Labels: 🦁의성, ♻️Refactoring
